/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "log-viewer.hosts": [],
    "log-viewer.folders": [],
    "log-viewer.folders.request-download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.clear-cache": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.delete": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files": [],
    "log-viewer.files.request-download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.delete": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache-all": [],
    "log-viewer.files.delete-multiple-files": [],
    "log-viewer.logs": [],
    "log-viewer.folders.download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "dashboard": [],
    "playground": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
