name: lint

on:
  push:
    branches:
      - development
      - main
    paths-ignore:
      - '.gitignore'
      - 'laradumps.yaml'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - development
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install Node Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-install=dist

      - name: Lint
        run: composer run lint
